### ISSUE TITLE
AttributeError: module 'sqlalchemy.types' has no attribute 'Binary'

### ISSUE THREAD

**Issue by pathnames** [blakev/Flask-WhooshAlchemy3#13]
With the latest update to SQLAlchemy (1.4.22), the class `Binary` has been removed and replaced with` LargeBinary`. This change needs to be made in `__init__.py`. 

Source: [Official documentation](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-214869a306f72f33237772d33fc332ec)

**Comment by blakev** [comment]
ACK

Thanks for the find!
