### ISSUE TITLE
AttributeError: 'BaseQuery' object has no attribute 'search'

### ISSUE THREAD

**Issue by therealrobster** [blakev/Flask-WhooshAlchemy3#2]
Hi there,

Giving this a go.

Here is my config:

    # Database
    SQLALCHEMY_DATABASE_URI = 'sqlite:///db/site.db'
    # turning on tracking so the search extension can track if anything in the database changes
    SQL_TRACK_MODIFICATIONS = True

    # set the location for the whoosh index
    WHOOSH_INDEX_PATH = 'whooshIndex'
    WHOOSH_ANALYZER = 'StemmingAnalyzer'

My model:

    class Org(db.Model):
        __searchable__ = ['orgName', 'phone1', 'phone2', 'phone3', 'email1', 'email2', 'email3', 'backgroundInfo']
        __analyzer__ = StemmingAnalyzer()
        id = db.Column(db.Integer, primary_key=True)
        active = db.Column(db.Boolean, unique=False, default=True)
        orgName = db.Column(db.String(200), unique=True, nullable=False)
        posts = db.relationship('Log', backref='organisation', lazy=True)
        postalStreet = db.Column(db.String(200))
        postalTown = db.Column(db.String(60))
        postalState = db.Column(db.String(20))
        postalPostCode = db.Column(db.String(10))
        backgroundInfo = db.Column(db.String(1000))
        phone1 = db.Column(db.String(128))
        phone2 = db.Column(db.String(128))
        phone3 = db.Column(db.String(128))
        phone1Type = db.Column(db.String(24))
        phone2Type = db.Column(db.String(24))
        phone3Type = db.Column(db.String(24))
        email1 = db.Column(db.String(128))
        email2 = db.Column(db.String(128))
        email3 = db.Column(db.String(128))
        email1Type = db.Column(db.String(24))
        email2Type = db.Column(db.String(24))
        email3Type = db.Column(db.String(24))

        def __repr__(self):  # this is how our object is printed when we print it out
            return f"Org('{self.orgName}')"

If I add data it creates the index files.  I can see them being created in the file system.  All good from that end.

Here is my search code in a view:

    num_posts = min(request.args.get('limit', 10), 50)
    query = request.args.get('q', '')
    results = Org.query.search(query, limit=num_posts)

It's returning `AttributeError: 'BaseQuery' object has no attribute 'search'`

I've done a heap of searching but am coming up empty.  Can you spot what the issue is?

Thank you

**Comment by therealrobster** [comment]
An update to this.  I've updated the models with the `__tablename__` also and I've added Flask-WhooshAlchemy3 via Dockerfile as such `RUN pip install git+git://github.com/blakev/Flask-WhooshAlchemy3.git@master` to ensure the latest but it's still happening.  

`AttributeError: 'BaseQuery' object has no attribute 'search'` when I try and do a search:

    num_posts = min(request.args.get('limit', 10), 50)
    query = request.args.get('q', '')
    results = Org.query.search(query, limit=num_posts)

**Comment by blakev** [comment]
I cannot duplicate. 

https://i.imgur.com/dQ3ucGN.png

```shell
(Flask-WhooshAlchemy3) [blake@bv-desktop ~]$ python
Python 3.7.4 (default, Jul 16 2019, 07:12:58)
[GCC 9.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

Try this,

```python
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# >>
#     Flask-WhooshAlchemy3, 2017
# <<

import random
from flask import Flask, request
from flask_sqlalchemy import SQLAlchemy
import flask_whooshalchemy

from whoosh.analysis import StemmingAnalyzer
app = Flask(__name__)
app.config.update(dict(
    SQLALCHEMY_DATABASE_URI='sqlite:///db.sqlite',
    SQL_TRACK_MODIFICATIONS=True,
    WHOOSH_INDEX_PATH='whooshIndex',
    WHOOSH_ANALYZER='StemmingAnalyzer',
))

db = SQLAlchemy()


class Org(db.Model):
    __searchable__ = ['orgName', 'phone1', 'phone2', 'phone3', 'email1', 'email2', 'email3', 'backgroundInfo']
    __analyzer__ = StemmingAnalyzer()
    __tablename__ = 'Org'

    id = db.Column(db.Integer, primary_key=True)
    active = db.Column(db.Boolean, unique=False, default=True)
    orgName = db.Column(db.String(200), unique=True, nullable=False)
    postalStreet = db.Column(db.String(200))
    postalTown = db.Column(db.String(60))
    postalState = db.Column(db.String(20))
    postalPostCode = db.Column(db.String(10))
    backgroundInfo = db.Column(db.String(1000))
    phone1 = db.Column(db.String(128))
    phone2 = db.Column(db.String(128))
    phone3 = db.Column(db.String(128))
    phone1Type = db.Column(db.String(24))
    phone2Type = db.Column(db.String(24))
    phone3Type = db.Column(db.String(24))
    email1 = db.Column(db.String(128))
    email2 = db.Column(db.String(128))
    email3 = db.Column(db.String(128))
    email1Type = db.Column(db.String(24))
    email2Type = db.Column(db.String(24))
    email3Type = db.Column(db.String(24))

    def __repr__(self):  # this is how our object is printed when we print it out
        return f"Org('{self.orgName}')"


@app.route('/search')
def search():
    num_posts = min(int(request.args.get('limit', 10)), 50)
    query = request.args.get('q', '')
    results = Org.query.search(query, limit=num_posts)
    return '\n'.join(map(str, results))


BOOL = (True, False,)
STATES = ('UT', 'ID', 'CA', 'CO', 'WY', 'AR', 'NV',)
NAMES = ('Red', 'Green', 'Blue', 'Yellow',)

@app.before_first_request
def bootstrap():
    db.create_all()
    flask_whooshalchemy.search_index(app, Org)

    for x in range(100):
        rec = Org(active=random.choice(BOOL),
                  orgName=f'{random.choice(NAMES)}_{x}',
                  postalState=random.choice(STATES),
                  postalStreet=random.randrange(100, 1500))
        db.session.add(rec)
    db.session.commit()


if __name__ == "__main__":
    db.init_app(app)
    app.run()
```

**Comment by therealrobster** [comment]
Thanks for such a thorough reply.

I've given it a good go today.  Below is some cropped code to focus on the search logic.  

```
from logrr import app
import flask_whooshalchemy
from flask import Blueprint, render_template, flash, redirect, url_for, request, abort
# lots of other imports etc here RE databases, models, etc

@org.before_request
def before_request():
    if current_user.is_authenticated:
        # other stuff I do on auth
        flask_whooshalchemy.search_index(app, Org)

# search the organisations
@org.route('/orgSearch')
@login_required
def search():

    num_posts = min(int(request.args.get('limit', 10)), 50)
    query = request.args.get('q', '')
    results = Org.query.search(query, limit=num_posts)
    return '\n'.join(map(str, results))

```
So at this point I get a different error based on the `flask_whooshalchemy.search_index(app, Org)` line.  That gives the following error:

    File "/usr/local/lib/python3.7/site-packages/flask_whooshalchemy/__init__.py", line 241, in search_index model.__tablename__, create_index(app, model))
    File "/usr/local/lib/python3.7/site-packages/flask_whooshalchemy/__init__.py", line 169, in create_index path = app.config.get('WHOOSH_INDEX_PATH', DEFAULT_WHOOSH_INDEX_PATH)
    AttributeError: module 'logrr.app' has no attribute 'config'

I do have a config area of my app, but I assume the whooshalchemy is expecting it somewhere else perhaps?  I'm a little new to be digging that deeply sorry.

So at this point I'm sort of stuck at that point.

If I remove the offending line, I end up with the original error.

**Comment by therealrobster** [comment]
This is my project structure if it helps.  You'll see I have my config located under `/config/settings.py`

    .
    ├── config
    │   ├── __init__.py
    │   └── settings.py
    ├── docker-compose.override.yml
    ├── docker-compose.yml
    ├── Dockerfile
    ├── instance
    │   ├── __init__.py
    │   └── settings.py
    ├── logrr
    │   ├── app.py
    │   ├── blueprints
    │   │   ├── admin
    │   │   │   ├── __init__.py
    │   │   │   ├── templates
    │   │   │   │   └── admin
    │   │   │   │       ├── admin.html
    │   │   │   │       └── adminTools.html
    │   │   │   └── views.py
    │   │   ├── errors
    │   │   │   ├── handlers.py
    │   │   │   ├── __init__.py
    │   │   │   └── templates
    │   │   │       └── errors
    │   │   │           ├── 403.html
    │   │   │           ├── 404.html
    │   │   │           └── 500.html
    │   │   ├── home
    │   │   │   ├── __init__.py
    │   │   │   ├── templates
    │   │   │   │   └── home
    │   │   │   │       └── home.html
    │   │   │   └── views.py
    │   │   ├── __init__.py
    │   │   ├── login
    │   │   │   ├── forms.py
    │   │   │   ├── __init__.py
    │   │   │   ├── templates
    │   │   │   │   └── login
    │   │   │   │       ├── account.html
    │   │   │   │       ├── login.html
    │   │   │   │       ├── reset_request.html
    │   │   │   │       └── reset_token.html
    │   │   │   ├── utils.py
    │   │   │   └── views.py
    │   │   ├── org
    │   │   │   ├── forms.py
    │   │   │   ├── __init__.py
    │   │   │   ├── templates
    │   │   │   │   └── org
    │   │   │   │       ├── create_log.html
    │   │   │   │       ├── organisation_add.html
    │   │   │   │       ├── organisation_list.html
    │   │   │   │       ├── organisation_view.html
    │   │   │   │       ├── user_posts.html
    │   │   │   │       └── view_log.html
    │   │   │   └── views.py
    │   │   ├── __pycache__
    │   │   │   └── __init__.cpython-37.pyc
    │   │   └── register
    │   │       ├── forms.py
    │   │       ├── __init__.py
    │   │       ├── templates
    │   │       │   └── register
    │   │       │       └── register.html
    │   │       └── views.py
    │   ├── db
    │   │   └── site.db
    │   ├── extensions.py
    │   ├── __init__.py
    │   ├── logs
    │   ├── models.py
    │   ├── static
    │   ├── templates
    │   │   ├── layouts
    │   │   │   ├── base.html
    │   │   └── macros
    │   │       ├── flash.html
    │   │       └── form.html
    │   └── uploads
    ├── README.md
    ├── requirements.txt
    ├── ssl
    ├── traefik.toml
    └── whooshSearch
        ├── log
        │   ├── _MAIN_18245.toc
        │   ├── MAIN_2ihbkztp6ru2nhzc.seg
        │   ├── MAIN_2ka4h5ukrwro8vxg.seg
        │   ├── MAIN_4rf7d6rhrc4qfh6l.seg
        │   ├── MAIN_4wuxcaoiec88y8dy.seg
        │   ├── MAIN_6xwgomvbk3434a63.seg
        │   ├── MAIN_cl4168sgsqdngh2u.seg
        │   ├── MAIN_g1nw5qi33y29pmow.seg
        │   ├── MAIN_ghrtymc8b9uth9vi.seg
        │   ├── MAIN_jvsyehu5okp8ruek.seg
        │   ├── MAIN_w1tkmt54avh1ekz2.seg
        │   ├── MAIN_WRITELOCK
        │   └── MAIN_zzxtvutj6s2hfu7f.seg
        └── org
            ├── MAIN_3dtx7zds22f6n3me.seg
            ├── _MAIN_410.toc
            ├── MAIN_4t717mgfrfw9k7se.seg
            ├── MAIN_52oil2m97vdj9xu7.seg
            ├── MAIN_5g67mzz3dgbamppm.seg
            ├── MAIN_eyqnuunv8usf5y6z.seg
            ├── MAIN_fq4kuq4d1egl4zwh.seg
            ├── MAIN_WRITELOCK
            └── MAIN_x5uum318ei3kc3z6.seg

**Comment by therealrobster** [comment]
I do have a config setup in a file called `settings.py` and it has the following (and more):

    # Database
    SQLALCHEMY_DATABASE_URI = 'sqlite:///db/site.db'
    # turning on tracking so the search extension can track if anything in the database changes
    SQL_TRACK_MODIFICATIONS = True


    # Search
    WHOOSH_ANALYZER = 'StemmingAnalyzer'
    WHOOSH_INDEX_PATH = 'whooshSearch'

Here is my tree if it helps understand my project:

    ├── config
    │   ├── __init__.py
    │   └── settings.py
    ├── docker-compose.override.yml
    ├── docker-compose.yml
    ├── Dockerfile
    ├── instance
    │   ├── __init__.py
    │   └── settings.py
    ├── logrr
    │   ├── app.py
    │   ├── blueprints
    │   │   ├── admin
    │   │   │   ├── __init__.py
    │   │   │   ├── templates
    │   │   │   │   └── admin
    │   │   │   │       ├── admin.html
    │   │   │   │       └── adminTools.html
    │   │   │   └── views.py
    │   │   ├── errors
    │   │   │   ├── handlers.py
    │   │   │   ├── __init__.py
    │   │   │   └── templates
    │   │   │       └── errors
    │   │   │           ├── 403.html
    │   │   │           ├── 404.html
    │   │   │           └── 500.html
    │   │   ├── home
    │   │   │   ├── __init__.py
    │   │   │   ├── templates
    │   │   │   │   └── home
    │   │   │   │       └── home.html
    │   │   │   └── views.py
    │   │   ├── __init__.py
    │   │   ├── login
    │   │   │   ├── forms.py
    │   │   │   ├── __init__.py
    │   │   │   ├── templates
    │   │   │   │   └── login
    │   │   │   │       ├── account.html
    │   │   │   │       ├── login.html
    │   │   │   │       ├── reset_request.html
    │   │   │   │       └── reset_token.html
    │   │   │   ├── utils.py
    │   │   │   └── views.py
    │   │   ├── org
    │   │   │   ├── forms.py
    │   │   │   ├── __init__.py
    │   │   │   ├── templates
    │   │   │   │   └── org
    │   │   │   │       ├── create_log.html
    │   │   │   │       ├── organisation_add.html
    │   │   │   │       ├── organisation_list.html
    │   │   │   │       ├── organisation_view.html
    │   │   │   │       ├── user_posts.html
    │   │   │   │       └── view_log.html
    │   │   │   └── views.py
    │   │   └── register
    │   │       ├── forms.py
    │   │       ├── __init__.py
    │   │       ├── templates
    │   │       │   └── register
    │   │       │       └── register.html
    │   │       └── views.py
    │   ├── db
    │   │   └── site.db
    │   ├── extensions.py
    │   ├── __init__.py
    │   ├── logs
    │   ├── models.py
    │   ├── static
    │   ├── templates
    │   │   ├── layouts
    │   │   │   ├── base.html
    │   │   └── macros
    │   │       ├── flash.html
    │   │       └── form.html
    │   └── uploads
    ├── README.md
    ├── requirements.txt
    ├── ssl
    ├── traefik.toml
    └── whooshSearch
        ├── log
        │   ├── _MAIN_18245.toc
        │   ├── MAIN_2ihbkztp6ru2nhzc.seg
        │   ├── MAIN_2ka4h5ukrwro8vxg.seg
        │   ├── MAIN_4rf7d6rhrc4qfh6l.seg
        │   ├── MAIN_4wuxcaoiec88y8dy.seg
        │   ├── MAIN_6xwgomvbk3434a63.seg
        │   ├── MAIN_cl4168sgsqdngh2u.seg
        │   ├── MAIN_g1nw5qi33y29pmow.seg
        │   ├── MAIN_ghrtymc8b9uth9vi.seg
        │   ├── MAIN_jvsyehu5okp8ruek.seg
        │   ├── MAIN_w1tkmt54avh1ekz2.seg
        │   ├── MAIN_WRITELOCK
        │   └── MAIN_zzxtvutj6s2hfu7f.seg
        └── org
            ├── MAIN_3dtx7zds22f6n3me.seg
            ├── _MAIN_410.toc
            ├── MAIN_4t717mgfrfw9k7se.seg
            ├── MAIN_52oil2m97vdj9xu7.seg
            ├── MAIN_5g67mzz3dgbamppm.seg
            ├── MAIN_eyqnuunv8usf5y6z.seg
            ├── MAIN_fq4kuq4d1egl4zwh.seg
            ├── MAIN_WRITELOCK
            └── MAIN_x5uum318ei3kc3z6.seg


Here also is part of my `app.py`:

    def create_app():

        # instance_relative_config tells flask to look for an instance module that's in the same folder depth as the main module
        app = Flask(__name__, instance_relative_config=True)

        # look for a settings.py file in the config folder
        app.config.from_object('config.settings')

        # look in the instance folder for settings.py.  Silent = True means don't crash if file doesn't exist
        # as instance settings is loaded after config settings, the instance settings will overide the config settings if duplicate settings exist
        app.config.from_pyfile('settings.py', silent=True)

        # set the upload folder
        UPLOAD_FOLDER = 'uploads'
        app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

        # routes
        app.register_blueprint(home)
        app.register_blueprint(register)
        app.register_blueprint(login)
        app.register_blueprint(admin)
        app.register_blueprint(org)
        app.register_blueprint(org)
        app.register_blueprint(errors)

        # extensions
        extensions(app)

        return app


and I would normally get a config variable like so:

    os.environ.get('WHOOSH_ANALYZER')
