### ISSUE TITLE
Issues with required version of SQLALchemy on Python 3.8+

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [blakev/Flask-WhooshAlchemy3#5]
Python 3.8 [removes the time.clock() function](https://docs.python.org/3/whatsnew/3.8.html). Recently SQLAlchemy [removed this code altogether](https://github.com/sqlalchemy/sqlalchemy/commit/0fff647a8f1fb863ec99195a65cf6e64ce204445#diff-b000fbab3c5b0ae3ee4b0501343e454b). As a result of the requirements.txt file specifying SQLALchemy version 1.3.12 Flask-WhooshAlchemy3 will not work on Python3.8+.

**Comment by blakev** [comment]
Fixed in version 0.2.0
