### ISSUE TITLE
Flask_whooshalchemy3 not indexing entries in blueprints

### ISSUE THREAD

**Issue by Ewetoye** [blakev/Flask-WhooshAlchemy3#7]
I have no problem when using flask_whooshalchemy3 without blueprints but with blueprints and factory function, either the indexes were not created or created but never searched.

Without Blueprint: Here is a portion of the view file, I called the flask_whooshalchemy3 search method in the before_first_request decorator.

```
from datetime import datetime
import json
import flask_whooshalchemy

from flask import render_template, request, abort, redirect, \
    url_for, flash
from werkzeug.urls import url_parse
from flask_security import Security, SQLAlchemyUserDatastore, \
    utils, login_required, login_user, logout_user, current_user
from flask_admin import Admin

from . import app
from .models import Article, Tag, db, User, Role, articles_tags, \
                    ArticleAdmin, TagAdmin, UserAdmin, RoleAdmin
from .forms import ArticleForm, LoginForm, RegistrationForm
from .utilities import split_article, update_article, can_edit
# ----------- Initializations----------------------------------
# Initialize the SQLAlchemy data store.
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
# Initialize Flask-Security.
Security(app, user_datastore)

# Executes before the first request is processed.
@app.before_first_request
def before_first_request():

    # Create any database tables that don't exist yet.
    db.create_all()
    # Indexing of articles to be search ready
    flask_whooshalchemy.search_index(app, Article)
```
With Blueprint: I called the search method in the app factory

```
from flask import Flask
from flask_admin import Admin
import flask_whooshalchemy
from flask_fileupload import FlaskFileUpload
from models import Article, Tag, db, User, Role, ArticleAdmin, \
                    TagAdmin, UserAdmin, RoleAdmin
from config import config

def create_app(config_name):
    app=Flask(__name__)
    app.config.from_object(config[config_name])
    db.init_app(app)
    db.reflect(app=app)
    # Initialize Flask-FileUpload.
    FlaskFileUpload(app)
    flask_whooshalchemy.search_index(app, Article)
    # Initialize Flask-Admin.
    admin = Admin(app)
    admin.add_view(ArticleAdmin(Article, db.session))
    admin.add_view(TagAdmin(Tag, db.session))
    admin.add_view(UserAdmin(User, db.session))
    admin.add_view(RoleAdmin(Role, db.session))
    # ----------- Initializations----------------------------------
    # Initialize the SQLAlchemy data store.
    from flask_security import Security, SQLAlchemyUserDatastore
    user_datastore = SQLAlchemyUserDatastore(db, User, Role)
    # Initialize Flask-Security.
    Security(app, user_datastore)
    from equimolar_blog.main_app import create_module
    with app.app_context():
        # Time to make sure roles exist in the database
        db.create_all()
        try:
            from create_db import create_roles
            create_roles(user_datastore, db)
        except ImportError:
            pass
        create_module(app)
    return app
```
I can't seem to point-out where the problem is.

**Comment by bartdegoede** [comment]
Did you set the `SQLALCHEMY_TRACK_MODIFICATIONS` config to `False`? Most applications don't use the Flask eventing system, and it adds some overhead to keep track of the changes. This particular [bit of code relies on the change signal](https://github.com/blakev/Flask-WhooshAlchemy3/blob/e653ac73397817d66e7d9633a4426cf3894e4d95/flask_whooshalchemy/__init__.py#L245) in order to pick up the changes: https://flask-sqlalchemy.palletsprojects.com/en/2.x/signals/

**Comment by Ewetoye** [comment]
Wow!!!

I got it after going through the [Signalling Support documentation](https://flask-sqlalchemy.palletsprojects.com/en/2.x/signals/) @bartdegoede.

relies on [models_committed](https://github.com/blakev/Flask-WhooshAlchemy3/blob/e653ac73397817d66e7d9633a4426cf3894e4d95/flask_whooshalchemy/__init__.py#L245) which emits signals when changed models were committed to the database and according to the documentation,
> changes are only tracked if SQLALCHEMY_TRACK_MODIFICATIONS is enabled in the config

The problem was solved by simply setting `SQLALCHEMY_TRACK_MODIFICATIONS=True` or not setting `SQLALCHEMY_TRACK_MODIFICATIONS` at all, as it defaults to True but I prefer to be explicit.

Thank you and I am closing this issue.
