### ISSUE TITLE
Flask' object has no attribute 'search_indexes'

### ISSUE THREAD

**Issue by inboxdarpan** [blakev/Flask-WhooshAlchemy3#8]
When I am trying to create new index,  using `flask_whooshalchemy.create_index(app, Store)`, it throws `Flask' object has no attribute 'search_indexes'`.

I used this function to create indexes because my hunch is that it replaces old `flask_whooshalchemy.whoosh_index(app, Store)` function. 

Though ReadMe file does not ask me to add `flask_whooshalchemy.create_index(app, Store)` at the end of the model I want to index, but if I don't do that, it throws me an error when I try to query using `MyModel.query.search(query_string)`

**Comment by emperor22** [comment]
I solved it by adding a function with `@app.before_first_request` decorator.

this is what i wrote:

    @app.before_first_request
        def initiate_index():
            flask_whooshalchemy.search_index(app, <ModelName>)

and I had to drop and recreate my database, so if you haven't tried doing one of them, just try it first.
